=== sebbouez/ExpressiveWeb/Schemas/schema_components.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Component">
        <xs:complexType>
          
            <xs:all>
                <xs:element name="UID" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            <![CDATA[
                            Unique name of the component in the Kit.
                            For example "MyKit.Button"
                            ]]>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Family" type="xs:string" minOccurs="0"/>
                <xs:element name="Allows" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            <![CDATA[
                            List of accepted children using their UID. Values must be separated by ';'.
                            If the component accepts any kind of children, use "*".
                            Examples:
                            <Allows>*</Allows>
                            <Allows>MyKit.Button;MyKit.Heading1</Allows>
                            ]]>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Denies" type="xs:string" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            <![CDATA[
                            List of refused children using their UID. Values must be separated by ';'.
                            If the component accepts any kind of children, use "*". 
                            Examples:
                            <Denies>*</Denies>
                            <Denies>MyKit.Button;MyKit.Heading1</Denies>
                            ]]>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Slots" type="xs:string" nillable="true" minOccurs="0"/>
                <xs:element name="Template" type="xs:string" />


                <xs:element name="Actions" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            <![CDATA[
                            This sections allows to specify the contextual actions that appear when the user selects the component in the designer.
                            ]]>
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Action" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Header" type="xs:string" use="required"/>
                                    <xs:attribute name="Command" type="xs:string" use="required"/>
                                    <xs:attribute name="Params" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>



                <xs:element name="Features" minOccurs="0" nillable="true">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="InlineEdit" minOccurs="0"/>
                            <xs:element name="SwapTextTag" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>
                                        <![CDATA[
                                        This feature allows the user to transform the text tag (headings and paragraphs) into another text tag (headings and paragraphs).
                                        For example:
                                        The user selects a P tag and then selects "Change to Heading 1".
                                        ]]>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="ContextualBoxStyle" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="EnableBorderSettings" type="xs:boolean" use="optional" default="false"/>
                                    <xs:attribute name="EnableBackgroundSettings" type="xs:boolean" use="optional" default="false"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:all>
                    </xs:complexType>
                </xs:element>
                        
            </xs:all>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/Components/heading4.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.Heading4</UID>
    <Name>Heading 4</Name>
    <Family>headings</Family>
    
    <Features>
        <InlineEdit/>
        <SwapTextTag/>
    </Features>
    
    <Allows>text</Allows>


    <Template>
        <![CDATA[
        <h4>Some text</h4>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/Components/card-text.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.CardText</UID>
    <Name>Card text</Name>
 
    <Features>
        <InlineEdit/>
    </Features>

    <Actions>
    </Actions>
    
    <Allows>text</Allows>


    <Template>
        <![CDATA[
        <p class="card-text">Some text</p>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/bin/Debug/net9.0/Kits/Bootstrap5/Components/card-title.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.CardTitle</UID>
    <Name>Card title</Name>

    <Features>
        <InlineEdit/>
    </Features>
    
    <Allows>text</Allows>


    <Template>
        <![CDATA[
        <h5 class="card-title">Some text</p>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/bin/Debug/net9.0/Kits/Bootstrap5/Components/paragraph.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.Paragraph</UID>
    <Name>Paragraph</Name>
    <Family>paragraphs</Family>
    
    <Features>
        <InlineEdit/>
        <SwapTextTag/>
    </Features>
    
    <Allows>text</Allows>

    <Template>
        <![CDATA[
        <p>Some text</p>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/bin/Debug/net9.0/Kits/Bootstrap5/Components/col.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.Col</UID>
    <Name>Col</Name>

    <Actions>
        <Action Header="Add card" Command="AppendChild" Params="bootstrap.Card"/>
        <Action Header="Add row bellow" Command="AppendChild" Params="bootstrap.Card"/>
    </Actions>
    
    <Allows>bootstrap.Card;paragraphs;headings</Allows>

    <Template>
        <![CDATA[
        <div class="col">
            <slot/>
        </div>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/Components/col.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.Col</UID>
    <Name>Col</Name>

    <Actions>
        <Action Header="Add card" Command="AppendChild" Params="bootstrap.Card"/>
        <Action Header="Add heading 1" Command="AppendChild" Params="bootstrap.Heading1"/>
        <Action Header="Add heading 2" Command="AppendChild" Params="bootstrap.Heading2"/>
        <Action Header="Add heading 3" Command="AppendChild" Params="bootstrap.Heading3"/>
        <Action Header="Add paragraph" Command="AppendChild" Params="bootstrap.Paragraph"/>
    </Actions>

    <Allows>bootstrap.Card;paragraphs;headings</Allows>

    <Template>
        <![CDATA[
        <div class="col">
            <slot/>
        </div>
        ]]>
    </Template>

</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/Components/hyperlink.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.Hyperlink</UID>
    <Name>Hyperlink</Name>

    <Actions>
    </Actions>

    <Features>
        <InlineEdit/>
    </Features>
    
    <Allows>text</Allows>


    <Template>
        <![CDATA[
        <a>
        </a>
        ]]>
    </Template>
    
</Component>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/Components/card-footer.xml
<?xml version="1.0" encoding="utf-8" ?>
<Component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_components.xsd">

    <UID>bootstrap.CardFooter</UID>
    <Name>Card footer</Name>

    <Features>
        <InlineEdit/>
    </Features>
    
    <Allows>text</Allows>


    <Template>
        <![CDATA[
         <div class="card-footer">Footer</div>
        ]]>
    </Template>
    
</Component>
