=== sebbouez/ExpressiveWeb/Schemas/schema_kits.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Kit">
        <xs:complexType>

            <xs:all>
                <xs:element name="Name" type="xs:string"/>

                <xs:element name="Version" type="xs:string" nillable="true" minOccurs="0"/>
                <xs:element name="Template" type="xs:string"/>

                <xs:element name="BuildActions" minOccurs="0">
                    <xs:complexType>

                    </xs:complexType>
                </xs:element>

                <xs:element name="DefaultPackages" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PackageReference" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Name" type="xs:string" use="required"/>
                                    <xs:attribute name="Version" type="xs:string" use="required"/>
                                    <xs:attribute name="Provider" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


            </xs:all>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== sebbouez/ExpressiveWeb/ExpressiveWeb.Kits/Kits/Bootstrap5/kit.xml
<?xml version="1.0" encoding="utf-8"?>

<Kit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/sebbouez/ExpressiveWeb/refs/heads/main/Schemas/schema_kits.xsd">

    <Name>Bootstrap 5</Name>
    <Version>1.0.0.0</Version>

    <DefaultPackages>
        <PackageReference Name="bootstrap" Version="5.3.7" Provider="JsDeliver"/>
    </DefaultPackages>

    <Templates>
        <Template Name="Editor demo page" File="Default.html" />
    </Templates>
    
    <BuildActions>


    </BuildActions>

</Kit>
